- name: Init pgbouncer configuration
  hosts: all

  tasks:
    - name: Create pgbouncer folder
      shell: mkdir -p /home/osboxes/pgbouncer

    - name: Create userlist.txt file
      shell: |
        cat << 'EOF' > /home/osboxes/pgbouncer/userlist.txt
        "yugabyte" ""
        EOF

    - name: Create pgbouncer.ini file
      shell: |
        cat << 'EOF' > /home/osboxes/pgbouncer/pgbouncer.ini
        [databases]
        * = host={{ ansible_host }} port=5433

        [pgbouncer]
        # Basic settings
        listen_addr = 0.0.0.0
        listen_port = 6432
        auth_type = trust
        auth_file = /etc/pgbouncer/userlist.txt

        # Connection settings
        pool_mode = transaction
        max_client_conn = 300
        default_pool_size = 150
        min_pool_size = 10
        EOF