- name: Start pgbouncer docker container
  hosts: all

  tasks:
    - name: Stop pgbouncer docker container
      shell: docker stop pgbouncer
      ignore_errors: true

    - name: Remove pgbouncer docker container
      shell: docker rm pgbouncer
      ignore_errors: true

    - name: Start pgbouncer docker container
      shell: |
        docker run --name pgbouncer --restart unless-stopped -d \
          -e DATABASE_URL="" \
          -p 6432:6432 \
          -v /home/osboxes/pgbouncer:/etc/pgbouncer \
          edoburu/pgbouncer