- name: Start yugabyte docker container
  hosts: all

  tasks:
    - name: Stop yugabyte docker container
      shell: docker stop yugabyte

    - name: Start yugabyte docker container
      shell: docker start yugabyte

    - name: Restart yugabyte to reset vCPU usage
      shell: docker restart yugabyte