- name: Start pgbouncer docker container
  hosts: all

  tasks:
    - name: Stop pgbouncer docker container
      shell: docker stop pgbouncer

    - name: Remove pgbouncer docker container
      shell: docker rm pgbouncer

    - name: Start pgbouncer docker container
      shell: |
        docker run --name pgbouncer --restart unless-stopped -d \
          -e DATABASE_URL="" \
          -p 6432:6432 \
          -v /home/osboxes/pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini \
          edoburu/pgbouncer